In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

vinos = pd.read_csv('vino.csv')

y = vinos['Wine Type']
x = vinos.drop('Wine Type', axis=1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

from sklearn.ensemble import RandomForestClassifier
arbol = RandomForestClassifier(n_estimators=80)

arbol.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=80, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [3]:
predicciones  = arbol.predict(x_test)


In [4]:

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predicciones))

[[19  0  0]
 [ 0 14  0]
 [ 0  0 21]]
