In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

flores = sns.load_dataset('iris')

x = flores.drop('species', axis=1)

y = flores['species']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

from sklearn.svm import SVC

modelo = SVC(gamma='auto')

modelo.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [2]:
predicciones  = modelo.predict(x_test)


from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predicciones))

[[16  0  0]
 [ 0 13  0]
 [ 0  0 16]]


In [3]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        16

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

