In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

vinos = pd.read_csv('vino.csv')

y = vinos['Wine Type']
x = vinos.drop('Wine Type', axis=1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

from sklearn.tree import DecisionTreeClassifier

arbol = DecisionTreeClassifier()

arbol.fit(x_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [3]:
predicciones  = arbol.predict(x_test)


In [4]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predicciones))

[[17  0  2]
 [ 0 13  1]
 [ 0  0 21]]


In [5]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      0.89      0.94        19
       Three       1.00      0.93      0.96        14
         Two       0.88      1.00      0.93        21

   micro avg       0.94      0.94      0.94        54
   macro avg       0.96      0.94      0.95        54
weighted avg       0.95      0.94      0.94        54

