# Cómo trabajar con matrices

In [3]:
import tensorflow as tf
session = tf.Session()

## 1. crear matrices

In [23]:
identity = tf.diag([1.,1.,1.,1.])


In [24]:
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[ 0.0168976   0.4756344  -1.7303039  -0.4928346 ]
 [ 0.00862244 -0.02161424  0.49059817 -1.9331378 ]
 [-1.032359   -1.71801     0.05436638 -0.31526518]]


In [13]:
B = tf.fill([3,4], 1995.)
print(session.run(B))

[[1995. 1995. 1995. 1995.]
 [1995. 1995. 1995. 1995.]
 [1995. 1995. 1995. 1995.]]


In [11]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.74842334 0.07637167 0.37587845]
 [0.15328133 0.08178461 0.4235791 ]
 [0.28082693 0.2962942  0.3913616 ]
 [0.34193003 0.8457885  0.9836607 ]]


In [12]:
import numpy as np
data = np.array([[1.,2.,3.,],[4.,5.,6.,],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar matrices

In [14]:
print(session.run(A+B))

[[1995.391  1994.9722 1996.6385 1994.5547]
 [1995.3888 1993.5048 1996.0248 1995.0482]
 [1994.087  1996.0375 1995.4049 1993.4457]]


In [15]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
print(session.run(tf.matmul(A,C)))

[[ 0.2614999   0.8777257   0.7458458 ]
 [ 0.19619066  0.16878952 -0.3936    ]
 [-0.98196304 -0.42705733 -0.8389224 ]]


## 3. Transpuesta, determianante, inversa

In [17]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [18]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3., -6., -1.], [0., 5, -3]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [20]:
N = session.run(tf.matrix_inverse(E))

In [21]:
print(session.run(tf.matmul(E,N)))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]


In [25]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
